import sampleImage from "../assets/milk_sample_image.jpeg";

export const products = [
  {
    id: 1,
    name: "Full Cream Milk",
    price: 3.0,
    description: "Rich and creamy full cream milk",
    inStock: true,
    imageUrl: sampleImage,
    snf: "8%",
    fatContent: "6.0%",
    quantity: 50,
  },
  {
    id: 2,
    name: "Skimmed Milk",
    price: 2.5,
    description: "Low-fat skimmed milk for a healthy lifestyle",
    inStock: false,
    imageUrl: sampleImage,
    snf: "7.75%",
    fatContent: "0.5%",
    quantity: 0,
  },
  {
    id: 3,
    name: "Almond Milk",
    price: 4.0,
    description: "Dairy-free almond milk, perfect for vegans",
    inStock: true,
    imageUrl: sampleImage,
    snf: "7.50%",
    fatContent: "2.0%",
    quantity: 30,
  },
  {
    id: 4,
    name: "Paneer",
    price: 5.5,
    description: "Fresh Indian cottage cheese (paneer)",
    inStock: true,
    imageUrl: sampleImage,
    snf: "8.25%",
    fatContent: "20.0%",
    quantity: 40,
  },
  {
    id: 5,
    name: "Greek Yogurt",
    price: 4.5,
    description: "Creamy and thick Greek yogurt",
    inStock: false,
    imageUrl: sampleImage,
    snf: "7%",
    fatContent: "10.0%",
    quantity: 0,
  },
  {
    id: 6,
    name: "Shrikhand",
    price: 6.0,
    description: "Traditional sweetened yogurt dessert",
    inStock: true,
    imageUrl: sampleImage,
    snf: "9%",
    fatContent: "8.0%",
    quantity: 20,
  },
  {
    id: 7,
    name: "Amrakhand",
    price: 7.0,
    description: "Mango flavored shrikhand, a summer delight",
    inStock: false,
    imageUrl: sampleImage,
    snf: "8.75%",
    fatContent: "8.5%",
    quantity: 0,
  },
  {
    id: 8,
    name: "Buttermilk",
    price: 2.0,
    description: "Refreshing and tangy buttermilk",
    inStock: true,
    imageUrl: sampleImage,
    snf: "7.25%",
    fatContent: "1.0%",
    quantity: 60,
  },
  {
    id: 9,
    name: "Condensed Milk",
    price: 3.5,
    description: "Sweetened condensed milk for desserts",
    inStock: false,
    imageUrl: sampleImage,
    snf: "9.25%",
    fatContent: "28.0%",
    quantity: 0,
  },
  {
    id: 10,
    name: "Ghee",
    price: 8.0,
    description: "Pure clarified butter (ghee) for cooking",
    inStock: true,
    imageUrl: sampleImage,
    snf: "7.75%",
    fatContent: "99.8%",
    quantity: 25,
  },
  {
    id: 11,
    name: "Lassi",
    price: 3.0,
    description: "Traditional Indian yogurt drink",
    inStock: false,
    imageUrl: sampleImage,
    snf: "7.50%",
    fatContent: "3.0%",
    quantity: 0,
  },
  {
    id: 12,
    name: "Ricotta Cheese",
    price: 5.5,
    description: "Soft and creamy ricotta cheese",
    inStock: true,
    imageUrl: sampleImage,
    snf: "7.25%",
    fatContent: "13.0%",
    quantity: 15,
  },
  {
    id: 13,
    name: "Sour Cream",
    price: 3.5,
    description: "Rich and tangy sour cream",
    inStock: false,
    imageUrl: sampleImage,
    snf: "8.50%",
    fatContent: "20.0%",
    quantity: 0,
  },
  {
    id: 14,
    name: "Cottage Cheese",
    price: 4.0,
    description: "Fresh and soft cottage cheese",
    inStock: true,
    imageUrl: sampleImage,
    snf: "7%",
    fatContent: "10.0%",
    quantity: 10,
  },
  {
    id: 15,
    name: "Kesar Peda",
    price: 6.5,
    description: "Traditional Indian milk-based sweet with saffron",
    inStock: true,
    imageUrl: sampleImage,
    snf: "9.50%",
    fatContent: "5.0%",
    quantity: 35,
  },
];
export const branches = [
  { id: "branch1", location: "Downtown Dairy Store" },
  { id: "branch2", location: "Suburb Outlet" },
  { id: "branch3", location: "City Center Dairy" },
];